version: "3.9"
services:
    db:
        container_name: mysqldb
        image: "mysql"
        restart: unless-stopped
        ports:
            - 3306:3306
        env_file:
            - .env
        volumes:
            - "./mysqldata:/var/lib/mysql"

volumes:
    mysqldata:
